# Generated by Django 4.2.23 on 2025-07-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('wallet_address', models.CharField(max_length=42)),
                ('target_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('raised_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Environment', 'Environment'), ('Poverty', 'Poverty'), ('Disaster Relief', 'Disaster Relief'), ('Animal Welfare', 'Animal Welfare'), ('Human Rights', 'Human Rights'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('creator_name', models.CharField(max_length=100)),
                ('creator_email', models.EmailField(max_length=254)),
                ('gov_id_hash', models.CharField(blank=True, max_length=100)),
                ('approval_doc_hash', models.CharField(blank=True, max_length=100)),
                ('gov_id_url', models.URLField(blank=True)),
                ('approval_doc_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('creator_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Charities',
                'db_table': 'charities',
            },
        ),
    ]
