# Generated by Django 4.2.23 on 2025-08-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='on_chain_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
