# Generated by Django 4.2.23 on 2025-07-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='charities.charity')),
            ],
            options={
                'db_table': 'donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
